KL_recon_plot_name: plot.png
agent_goal_weight: 5
algo_data_path: datasets/algo_mazes_50_walls.npy
algo_mix_ratio: 0.0
anneal_steps: 400000
batch_size: 32
beta_max: 10.0
checkpoint_dir: checkpoints_clutr_aligned
embed_dim: 300
enable_vertex_tracking: true
eval_metric_freq: 5000
gcp_bucket: ucl-ued-project-bucket
gcp_bucket_prefix: vae
gcp_project: open-endedness-ued-project
latent_dim: 64
learning_rate: 5.0e-05
num_steps: 5000000
platform: gcp
plot_freq: 1000
recon_added_weight_factor: 1.0
recon_weight: 1000
resume_run_id: null
run_id: 20260309_091933_lr5e-05_lat64_clutr_aligned_rw1000_beta10.0
run_tag: clutr_aligned_rw1000_beta10.0
save_freq: 20000
scale_latent: true
seq_len: 52
train_data_path: datasets/train_1M_envs.npy
vae_folder: vae
validation_data_path: datasets/new_val_20k_envs.npy
vertex_experiment_name: projects/852796889575/locations/europe-west4/tensorboards/7623353920022118400
vertex_experiment_region: europe-west4
vocab_size: 170
wall_weight: 1
working_path: /home/rhautier/superintelligence
