"""LLMInjectionManager orchestrator for periodic LLM maze injection into PLR buffer.

Encapsulates the full injection pipeline:
  1. Extract reference mazes from live PLR buffer state
  2. Call LLM to generate n_raw candidate mazes
  3. Validate each candidate (format + BFS path length > 5 + border walls)
  4. Amplify via wall-flip mutations, filter by solvability
  5. Batch-insert accepted levels into PLR buffer with max-priority score
  6. Log all injection metrics to WandB

This is the only LLM-related code that the training loop interacts with. The
training loop calls maybe_inject(runner_state, eval_step) at each eval step and
the injector handles all internal scheduling logic.

On any LLM API failure, training crashes immediately (no silent skip or retry
beyond MazeGenerator's configured max_retries).
"""

import collections
import logging
import time
from typing import List, Optional, Tuple

import jax
import jax.numpy as jnp
import numpy as np
import wandb

from llm.buffer_stats import BufferStatsExtractor
from llm.decision_gate import DiversityThresholds
from llm.injection_config import LLMInjectionConfig
from llm.level_cache import LevelCache
from llm.maze_generator import GenerationConfig, MazeGenerator
from jaxued.environments.maze.util import make_level_mutator_minimax
from jaxued.level_sampler import LevelSampler

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# BFS utility (numpy-side, used for validation and solvability checks)
# ---------------------------------------------------------------------------

def _bfs_path_length(wall_map_np: np.ndarray, start: Tuple[int, int], goal: Tuple[int, int]) -> int:
    """Compute BFS shortest path length from start to goal on the wall map.

    Args:
        wall_map_np: bool array shape (H, W), True = wall
        start: (x, y) tuple of start position (agent_pos)
        goal: (x, y) tuple of goal position (goal_pos)

    Returns:
        Integer path length (number of steps). Returns -1 if no path exists.
    """
    H, W = wall_map_np.shape
    sx, sy = start
    gx, gy = goal

    if wall_map_np[sy, sx] or wall_map_np[gy, gx]:
        return -1

    if sx == gx and sy == gy:
        return 0

    visited = np.zeros((H, W), dtype=bool)
    visited[sy, sx] = True
    queue = collections.deque()
    queue.append((sx, sy, 0))

    directions = [(1, 0), (-1, 0), (0, 1), (0, -1)]
    while queue:
        x, y, dist = queue.popleft()
        for dx, dy in directions:
            nx, ny = x + dx, y + dy
            if 0 <= nx < W and 0 <= ny < H and not visited[ny, nx] and not wall_map_np[ny, nx]:
                if nx == gx and ny == gy:
                    return dist + 1
                visited[ny, nx] = True
                queue.append((nx, ny, dist + 1))

    return -1


# ---------------------------------------------------------------------------
# Level validation
# ---------------------------------------------------------------------------

def validate_llm_level(level) -> Tuple[bool, str]:
    """Validate a Level object generated by the LLM.

    Checks:
    1. is_well_formatted() — basic format (wall map binary, agent/goal valid, etc.)
    2. Border walls — all cells on outer border should be walls
    3. BFS path length > 5 — maze must provide meaningful navigation

    Args:
        level: Level object from Level.from_str()

    Returns:
        (is_valid, reason_string) tuple. is_valid=True means the level is accepted.
        reason_string is a human-readable rejection reason (empty if accepted).
    """
    # Check 1: basic format
    well_formatted = bool(np.asarray(level.is_well_formatted()))
    if not well_formatted:
        return False, "Level failed is_well_formatted() check"

    # Check 2: border walls — all outer-border cells must be walls
    wall_map_np = np.asarray(level.wall_map, dtype=bool)
    H, W = wall_map_np.shape
    border_ok = (
        wall_map_np[0, :].all()
        and wall_map_np[H - 1, :].all()
        and wall_map_np[:, 0].all()
        and wall_map_np[:, W - 1].all()
    )
    if not border_ok:
        return False, "Level is missing border walls on at least one edge"

    # Check 3: BFS path length > 5
    ap = (int(np.asarray(level.agent_pos[0])), int(np.asarray(level.agent_pos[1])))
    gp = (int(np.asarray(level.goal_pos[0])), int(np.asarray(level.goal_pos[1])))
    path_len = _bfs_path_length(wall_map_np, ap, gp)
    if path_len < 0:
        return False, "Level is unsolvable — no BFS path from agent to goal"
    if path_len <= 5:
        return False, f"Level BFS path length {path_len} is too short (must be > 5)"

    return True, ""


# ---------------------------------------------------------------------------
# LLMInjectionManager
# ---------------------------------------------------------------------------

class LLMInjectionManager:
    """Orchestrates periodic LLM maze injection into the PLR replay buffer.

    The manager is stateless between injection events except for configuration
    and the MazeGenerator instance. The training loop calls maybe_inject() at
    each eval step and this class handles all scheduling logic.

    Args:
        config: LLMInjectionConfig populated from CLI flags via from_config_dict()
        level_sampler: LevelSampler instance used in the training loop
        eval_freq: Number of training updates per eval step (config["eval_freq"])
    """

    def __init__(
        self,
        config: LLMInjectionConfig,
        level_sampler: LevelSampler,
        eval_freq: int,
        agent_evaluator=None,
        level_cache: Optional[LevelCache] = None,
        training_config: Optional[dict] = None,
    ) -> None:
        self.config = config
        self.level_sampler = level_sampler
        self.eval_freq = eval_freq
        self.agent_evaluator = agent_evaluator  # AgentEvaluator instance (None if gate disabled)
        self.level_cache = level_cache  # LevelCache instance (None if caching disabled)
        self.training_config = training_config  # mutable training config dict from maze_plr.py

        # Buffer stats extractor for reference maze selection
        self.buffer_stats = BufferStatsExtractor(
            n_references=config.n_reference_mazes,
            strategy=config.reference_maze_strategy,
            hybrid_difficulty_percentile=config.hybrid_difficulty_percentile,
        )

        # Initialize MazeGenerator from config
        gen_config = self._build_generation_config(config)
        self.generator = MazeGenerator(gen_config)

        # Load prompt metric config from YAML (controls which metrics appear in LLM prompt)
        self._prompt_metrics = None
        self._pairwise_metrics_cfg = None
        self._downsample_points = 20
        if config.config_path:
            import yaml
            with open(config.config_path) as f:
                yaml_cfg = yaml.safe_load(f) or {}
            self._prompt_metrics = yaml_cfg.get("prompt_metrics")
            self._pairwise_metrics_cfg = yaml_cfg.get("pairwise_metrics")
            self._downsample_points = yaml_cfg.get("downsample_points", 20)

        # Wall-flip mutation function (JAX-compiled)
        self.mutate_level = make_level_mutator_minimax(100)

        # Track next ancestor_id for online injection (incremented per LLM seed)
        self.next_ancestor_id = 0

        # Mutable fixed-distribution slot count (avoids wandb config immutability)
        self.fixed_dist_n_llm = 0

        # Cumulative counters for WandB logging
        self.total_injected = 0
        self.total_attempted = 0
        self.batch_all_rejected_count = 0  # Number of events where all gate attempts failed

    def _build_generation_config(self, config: LLMInjectionConfig) -> GenerationConfig:
        """Build a GenerationConfig from LLMInjectionConfig.

        If config_path is set, loads settings from the YAML file and overrides
        provider/model from CLI flags if they were explicitly set.
        """
        gen_kwargs = {}

        # Load from YAML config file if provided
        if config.config_path:
            import yaml
            with open(config.config_path) as f:
                yaml_cfg = yaml.safe_load(f) or {}
            # Map top-level YAML fields to GenerationConfig fields
            field_map = {
                "provider": "provider",
                "model": "model",
                "temperature": "temperature",
                "max_retries": "max_retries",
                "timeout": "timeout",
                "max_tokens": "max_tokens",
                "thinking": "thinking",
                "thinking_budget": "thinking_budget",
                "thinking_in_output": "thinking_in_output",
                "min_walls": "min_walls",
                "min_path_distance": "min_path_distance",
                "validate_solvable": "validate_solvable",
                "effort": "effort",
            }
            for yaml_key, cfg_key in field_map.items():
                if yaml_key in yaml_cfg:
                    gen_kwargs[cfg_key] = yaml_cfg[yaml_key]

            # Resolve provider-specific base_url from YAML sub-dict
            provider_for_url = config.provider or yaml_cfg.get("provider", "ollama")
            if provider_for_url in yaml_cfg and isinstance(yaml_cfg[provider_for_url], dict):
                sub = yaml_cfg[provider_for_url]
                if "base_url" in sub and "base_url" not in gen_kwargs:
                    gen_kwargs["base_url"] = sub["base_url"]

        # CLI flags override YAML
        if config.provider:
            gen_kwargs["provider"] = config.provider
        if config.model:
            gen_kwargs["model"] = config.model

        return GenerationConfig(**gen_kwargs)

    def maybe_inject(self, runner_state: tuple, eval_step: int) -> tuple:
        """Entry point called at each eval step in the training loop.

        Implements injection scheduling: only injects when enabled, past warmup,
        and at the configured interval. All injection logic is in _do_injection().

        Args:
            runner_state: (rng, train_state) tuple — same structure as training loop
            eval_step: Current eval step index (0-based, increments each eval_freq updates)

        Returns:
            Potentially modified runner_state with updated train_state.sampler.
            Returned unchanged if injection is skipped.
        """
        if not self.config.enabled:
            return runner_state

        current_step = (eval_step + 1) * self.eval_freq

        if current_step < self.config.inject_start_step:
            return runner_state

        if current_step % self.config.injection_interval != 0:
            return runner_state

        print(f"[LLM] Injection event at step {current_step} (eval_step={eval_step})", flush=True)
        try:
            return self._do_injection(runner_state, current_step)
        except Exception as e:
            print(f"[LLM] Injection FAILED at step {current_step}: {e}. Training continues.", flush=True)
            return runner_state

    def _do_injection(self, runner_state: tuple, current_step: int) -> tuple:
        """Execute the full injection pipeline.

        Two code paths:
        - Gate enabled (gate_enabled=True, agent_evaluator set):
            Uses generate_with_feedback() which internally handles rollout,
            gate evaluation (difficulty+diversity), and feedback retry loop.
        - Gate disabled (gate_enabled=False or no agent_evaluator):
            Falls back to Phase 1 behavior: generate() + validate_llm_level().

        Steps:
        1. Refresh evaluator params from live train_state (gate path)
        2. Extract references (+ Level objects for gate path) and buffer summary
        3. Compute reference trajectories once at start (gate path)
        4. Generate n_raw candidate mazes via LLM using appropriate code path
        4b. Cache accepted LLM seeds to disk + collect hashes for WandB table
        5. Mutation amplification for each valid seed (optional)
        6. Batch-insert all accepted levels into PLR buffer with max-priority score
        7. Log WandB metrics including gate-specific metrics (GATE-03) and hash table

        Args:
            runner_state:  (rng, train_state) tuple
            current_step:  Current training step (used for caching file names)

        Returns:
            Updated runner_state with modified train_state.sampler
        """
        injection_start = time.time()
        rng, train_state = runner_state
        sampler = train_state.sampler

        gate_active = self.config.gate_enabled and self.agent_evaluator is not None

        # ---------------------------------------------------------------
        # Step 1: Refresh evaluator with live train_state params
        # ---------------------------------------------------------------
        if gate_active:
            self.agent_evaluator.update_params(train_state.params)

        # ---------------------------------------------------------------
        # Step 1b: Recompute buffer embeddings if buffer_state == "fresh"
        # ---------------------------------------------------------------
        if self.config.buffer_state == "fresh" and self.agent_evaluator is not None:
            buf_size = int(np.asarray(sampler["size"]))
            logger.info(f"[LLM] Recomputing buffer embeddings (fresh) for {buf_size} levels...")
            _t_fresh = time.time()
            from metrics.standalone.cenie import extract_state_action_pairs
            _be = getattr(self, '_buffer_embeddings', None)
            if _be is not None:
                levels_pytree = sampler["levels"]
                all_levels = [jax.tree_util.tree_map(lambda x: x[i], levels_pytree) for i in range(buf_size)]
                all_trajs = self.agent_evaluator.evaluate_levels(all_levels)
                for i, traj in enumerate(all_trajs):
                    pairs = extract_state_action_pairs(traj)
                    if pairs is not None and len(pairs) > 0:
                        _be[i] = pairs.mean(axis=0)
                    else:
                        _be[i] = 0.0
                logger.info(f"[LLM] Fresh embeddings computed in {time.time() - _t_fresh:.1f}s")

        # ---------------------------------------------------------------
        # Step 2: Extract references and buffer summary
        # ---------------------------------------------------------------
        # Pass buffer embeddings to extractor for kmedoid strategies
        buffer_embeddings_for_refs = getattr(self, '_buffer_embeddings', None)
        self.buffer_stats._buffer_embeddings = buffer_embeddings_for_refs

        if gate_active:
            references, ref_levels = self.buffer_stats.extract_references_with_levels(sampler)
        else:
            references = self.buffer_stats.extract_references(sampler)
            ref_levels = []

        buffer_summary = self.buffer_stats.extract_buffer_summary(sampler)
        global_metrics = BufferStatsExtractor.extract_global_metrics(buffer_summary)
        logger.debug(f"[LLM] Buffer: size={buffer_summary['buffer_size']}, "
                     f"mean_score={buffer_summary['mean_score']:.4f}")

        # ---------------------------------------------------------------
        # Step 3: Compute reference trajectories ONCE (gate path)
        # ---------------------------------------------------------------
        ref_trajectories = []
        ref_labels = []
        if gate_active and ref_levels:
            for ref, level in zip(references, ref_levels):
                traj = self.agent_evaluator.evaluate_level_multi_rollout(
                    level, n_rollouts=self.config.n_rollouts_gate
                )
                ref_trajectories.append(traj)
                ref_labels.append(ref.label)

            # Enrich references with trajectory-based metrics for the LLM prompt
            from llm.reference_metrics import enrich_references_with_metrics
            references, _ = enrich_references_with_metrics(
                references,
                trajectories=ref_trajectories,
                downsample_points=self._downsample_points,
                prompt_metrics=self._prompt_metrics,
                pairwise_metrics_cfg=self._pairwise_metrics_cfg,
            )

        # Fit CENIE model if using cenie diversity metric
        # Precompute reference embeddings for L2 embedding diversity
        ref_embeddings = None
        if gate_active and self.config.diversity_metric == "embedding_l2" and ref_trajectories:
            from metrics.standalone.cenie import extract_state_action_pairs
            ref_embs = []
            for traj in ref_trajectories:
                pairs = extract_state_action_pairs(traj)  # (T_ep, 257)
                if pairs is not None and len(pairs) > 0:
                    ref_embs.append(pairs.mean(axis=0))  # mean 257D embedding
            if ref_embs:
                ref_embeddings = np.stack(ref_embs)  # (n_refs, 257)
                logger.info(f"[LLM] Computed {len(ref_embs)} reference embeddings for L2 diversity")
            else:
                logger.warning("[LLM] No reference embeddings computed — diversity gate disabled")

        # Also pass buffer embeddings if available for broader coverage
        buffer_embeddings = getattr(self, '_buffer_embeddings', None)

        # Build DiversityThresholds from config (gate path)
        # Compute effective difficulty threshold based on gate mode
        buffer_size = int(np.asarray(sampler["size"]))
        buffer_scores = np.asarray(sampler["scores"][:buffer_size]) if buffer_size > 0 else np.array([0.0])

        mode = self.config.difficulty_gate_mode
        if mode == "fixed":
            effective_threshold = self.config.difficulty_threshold
        elif mode == "buffer_min":
            effective_threshold = float(buffer_scores.min())
        elif mode == "buffer_mean":
            effective_threshold = float(buffer_scores.mean())
        elif mode == "reference_mean":
            ref_scores = [r.metrics[0].value for r in references] if references else []
            effective_threshold = float(np.mean(ref_scores)) if ref_scores else 0.0
        elif mode == "competitive":
            effective_threshold = None  # no difficulty gate; seeds insert with actual score
        else:
            effective_threshold = self.config.difficulty_threshold

        # Compute effective diversity threshold based on diversity gate mode
        div_mode = self.config.diversity_gate_mode
        if div_mode == "fixed":
            effective_diversity = self.config.min_diversity
        elif div_mode == "buffer_median":
            # Median pairwise distance among reference trajectories
            if len(ref_trajectories) >= 2:
                from llm.decision_gate import _compute_pairwise_diversity
                pairwise_dists = []
                for a in range(len(ref_trajectories)):
                    for b in range(a + 1, len(ref_trajectories)):
                        d = _compute_pairwise_diversity(
                            ref_trajectories[a], ref_trajectories[b],
                            self.config.diversity_metric,
                        )
                        pairwise_dists.append(d)
                effective_diversity = float(np.median(pairwise_dists))
            else:
                effective_diversity = self.config.min_diversity  # fallback
        elif div_mode == "disabled":
            effective_diversity = None
        else:
            effective_diversity = self.config.min_diversity

        logger.info(f"[LLM] Difficulty gate: mode={mode}, threshold={effective_threshold}")
        logger.info(f"[LLM] Diversity gate: mode={div_mode}, threshold={effective_diversity}")

        thresholds = DiversityThresholds(
            difficulty_threshold=effective_threshold,
            difficulty_metric="sfl",
            min_diversity=effective_diversity,
            diversity_metric=self.config.diversity_metric,
        )

        # ---------------------------------------------------------------
        # Step 4: Generate n_raw candidate mazes via LLM
        # ---------------------------------------------------------------
        seeds_generated = self.config.n_raw
        valid_levels = []
        seed_sfl_scores = []  # actual SFL scores per accepted seed (for competitive mode)
        gate_accepted = 0
        gate_rejected = 0
        diversity_scores = []
        difficulty_scores = []
        # Per-accepted-seed embedding L2 distance stats
        emb_min_dists = []
        emb_mean_dists = []
        emb_max_dists = []
        emb_median_dists = []

        for i in range(seeds_generated):
            if gate_active:
                # Gated path: generate_with_feedback handles rollout+gate+retry internally
                result = self.generator.generate_with_feedback(
                    agent_evaluator=self.agent_evaluator,
                    reference_trajectories=ref_trajectories,
                    reference_labels=ref_labels,
                    references=references,
                    global_metrics=global_metrics,
                    diversity_thresholds=thresholds,
                    max_diversity_retries=self.config.max_diversity_retries,
                    n_rollouts=self.config.n_rollouts_gate,
                    ref_embeddings=ref_embeddings,
                    buffer_embeddings=buffer_embeddings,
                )
                if not result.success:
                    error_detail = "; ".join(result.errors) if result.errors else "unknown error"
                    print(
                        f"[LLM] generate_with_feedback() failed on maze {i+1}/{seeds_generated}: "
                        f"{error_detail}. Skipping this maze.",
                        flush=True,
                    )
                    gate_rejected += 1
                    continue
                # Check if gate ultimately accepted (no unresolved diversity issues)
                gate_metrics = result.gate_metrics or {}
                was_accepted = not result.diversity_issues
                if was_accepted:
                    gate_accepted += 1
                    valid_levels.append(result.level)
                    diversity_scores.append(float(gate_metrics.get("mean_diversity", 0.0)))
                    difficulty_scores.append(float(gate_metrics.get("regret", 0.0)))
                    seed_sfl_scores.append(float(gate_metrics.get("learnability", 0.0)))
                    # Embedding L2 distance stats
                    if "min_diversity" in gate_metrics and gate_metrics.get("diversity_metric") == "embedding_l2":
                        emb_min_dists.append(float(gate_metrics["min_diversity"]))
                        emb_mean_dists.append(float(gate_metrics.get("mean_diversity", 0.0)))
                        emb_max_dists.append(float(gate_metrics.get("max_diversity", 0.0)))
                        emb_median_dists.append(float(gate_metrics.get("median_diversity", 0.0)))
                else:
                    gate_rejected += 1
                    logger.info(f"[LLM] Seed {i+1} gate rejected: {result.diversity_issues}")
            else:
                # Ungated path (Phase 1 fallback): generate + validate_llm_level
                result = self.generator.generate(references=references, global_metrics=global_metrics)
                if not result.success:
                    error_detail = "; ".join(result.errors) if result.errors else "unknown error"
                    print(
                        f"[LLM] MazeGenerator.generate() failed on maze {i+1}/{seeds_generated}: "
                        f"{error_detail}. Skipping this maze.",
                        flush=True,
                    )
                    gate_rejected += 1
                    continue
                is_valid, reason = validate_llm_level(result.level)
                if is_valid:
                    gate_accepted += 1
                    valid_levels.append(result.level)
                else:
                    gate_rejected += 1
                    logger.info(f"[LLM] Seed {i+1} rejected: {reason}")

        seeds_valid = len(valid_levels)
        logger.info(f"[LLM] Seeds: {seeds_valid}/{seeds_generated} accepted "
                    f"(gate_accepted={gate_accepted}, gate_rejected={gate_rejected})")

        # Track batch events where all seeds were rejected
        if gate_accepted == 0 and seeds_generated > 0:
            self.batch_all_rejected_count += 1

        # ---------------------------------------------------------------
        # Step 4b: Cache accepted LLM seeds to disk + collect hashes
        # ---------------------------------------------------------------
        # Only LLM-generated seeds are cached — not mutations (per CONTEXT.md decision).
        # gate_metrics per seed: diversity_scores[i] / difficulty_scores[i] for gate path,
        # empty dict for ungated path.
        accepted_hashes = []
        if valid_levels:
            for idx, level in enumerate(valid_levels):
                gate_metrics_for_seed = {}
                if gate_active and idx < len(diversity_scores):
                    gate_metrics_for_seed = {
                        "mean_diversity": diversity_scores[idx],
                        "regret": difficulty_scores[idx],
                    }
                if self.level_cache is not None:
                    h = self.level_cache.save_accepted(level, current_step, idx, gate_metrics_for_seed)
                else:
                    h = LevelCache.compute_hash(level)
                accepted_hashes.append(h)

        # ---------------------------------------------------------------
        # Step 5: Mutation amplification (collected separately from seeds)
        # ---------------------------------------------------------------
        mutations_generated = 0
        mutations_solvable = 0
        mutations_prox_rejected = 0
        mutation_levels = []
        mutation_ancestor_ids = []

        # Compute seed embeddings for proximity gating of mutations
        prox_ratio = self.training_config.get("proximity_gate_ratio", 0) if self.training_config else 0
        seed_emb_cache = {}  # seed_idx -> (embedding, threshold)
        if prox_ratio > 0 and self.agent_evaluator is not None and valid_levels:
            # Compute organic centroid for threshold calculation
            buf_size = int(np.asarray(sampler["size"]))
            _be = getattr(self, '_buffer_embeddings', None)
            if _be is not None:
                nonzero = np.any(_be[:buf_size] != 0, axis=1)
                anc_ids = np.asarray(sampler["levels_extra"]["ancestor_id"][:buf_size])
                org_mask = (anc_ids < 0) & nonzero
                organic_centroid = _be[:buf_size][org_mask].mean(axis=0) if org_mask.any() else np.zeros(257)
            else:
                organic_centroid = np.zeros(257, dtype=np.float32)

            for si, level in enumerate(valid_levels):
                traj = self.agent_evaluator.evaluate_level_multi_rollout(
                    level, n_rollouts=self.config.n_rollouts_gate)
                from metrics.standalone.cenie import extract_state_action_pairs
                pairs = extract_state_action_pairs(traj)
                if pairs is not None and len(pairs) > 0:
                    emb = pairs.mean(axis=0)
                else:
                    emb = np.zeros(257, dtype=np.float32)
                dist = float(np.linalg.norm(emb - organic_centroid))
                seed_emb_cache[si] = (emb, prox_ratio * dist)

        # Assign ancestor IDs before mutation step (needed for mutation_ancestor_ids)
        seed_ancestor_ids = []
        for _ in valid_levels:
            seed_ancestor_ids.append(self.next_ancestor_id)
            self.next_ancestor_id += 1

        if self.config.amplification_enabled and valid_levels:
            # Determine mutation target: either fixed per-seed or fill-to-target
            target_pct = self.config.target_buffer_pct
            buf_capacity = int(sampler["scores"].shape[0])
            if target_pct > 0:
                # Target fill mode: generate mutations until buffer has target_pct LLM levels
                buf_size = int(np.asarray(sampler["size"]))
                target_total = max(1, int(target_pct * buf_capacity))
                # Count seeds already accepted (they'll be inserted)
                mutation_target = max(0, target_total - len(valid_levels))
                max_attempts = mutation_target * 10  # safety cap
                print(f"[LLM] Mutation target: {mutation_target} levels "
                      f"(target {target_total} = {target_pct:.0%} of {buf_capacity}, "
                      f"{len(valid_levels)} seeds, max {max_attempts} attempts)",
                      flush=True)
            else:
                # Fixed per-seed mode (original behavior)
                mutation_target = self.config.mutations_per_seed * len(valid_levels)
                max_attempts = mutation_target * 10

            n_seeds = len(valid_levels)
            seed_cycle = 0  # round-robin across seeds
            attempts = 0

            while len(mutation_levels) < mutation_target and attempts < max_attempts:
                seed_idx = seed_cycle % n_seeds
                seed_level = valid_levels[seed_idx]
                seed_cycle += 1

                # Generate a batch of mutations from this seed
                n_batch = min(50, max_attempts - attempts)
                attempts += n_batch
                mutations_generated += n_batch
                rng, mut_rng = jax.random.split(rng)
                mut_rngs = jax.random.split(mut_rng, n_batch)
                mutated_levels = jax.vmap(
                    lambda r: self.mutate_level(r, seed_level, 3)
                )(mut_rngs)

                # Filter by solvability (BFS, Python-side)
                wall_map_batch = np.asarray(mutated_levels.wall_map)
                agent_pos_batch = np.asarray(mutated_levels.agent_pos)
                goal_pos_batch = np.asarray(mutated_levels.goal_pos)

                for j in range(n_batch):
                    if len(mutation_levels) >= mutation_target:
                        break

                    if self.config.mutations_solvability_check:
                        wm = wall_map_batch[j]
                        ap = (int(agent_pos_batch[j, 0]), int(agent_pos_batch[j, 1]))
                        gp = (int(goal_pos_batch[j, 0]), int(goal_pos_batch[j, 1]))
                        path_len = _bfs_path_length(wm, ap, gp)
                        if path_len < 0:
                            continue

                    # Proximity gate: check L2 distance from parent seed
                    if seed_idx in seed_emb_cache and self.agent_evaluator is not None:
                        mutation = jax.tree_util.tree_map(lambda x: x[j], mutated_levels)
                        mut_traj = self.agent_evaluator.evaluate_level_multi_rollout(
                            mutation, n_rollouts=1)
                        from metrics.standalone.cenie import extract_state_action_pairs
                        mut_pairs = extract_state_action_pairs(mut_traj)
                        if mut_pairs is not None and len(mut_pairs) > 0:
                            mut_emb = mut_pairs.mean(axis=0)
                            seed_emb, threshold = seed_emb_cache[seed_idx]
                            dist = float(np.linalg.norm(mut_emb - seed_emb))
                            if dist > threshold:
                                mutations_prox_rejected += 1
                                continue
                    else:
                        mutation = jax.tree_util.tree_map(lambda x: x[j], mutated_levels)

                    mutation_levels.append(mutation)
                    # Track which seed this mutation came from
                    mutation_ancestor_ids.append(seed_ancestor_ids[seed_idx])

            mutations_solvable = len(mutation_levels)
            print(f"[LLM] Mutations: {mutations_solvable} accepted from "
                  f"{mutations_generated} generated ({attempts} attempts, "
                  f"{mutations_prox_rejected} proximity-rejected)", flush=True)

        if mutations_prox_rejected > 0:
            print(f"[LLM] Proximity gate rejected {mutations_prox_rejected} mutations", flush=True)

        total_levels_to_inject = len(valid_levels) + len(mutation_levels)
        logger.info(f"[LLM] Injecting {total_levels_to_inject} levels "
                    f"(seeds={seeds_valid}, mutations={mutations_solvable})")

        # ---------------------------------------------------------------
        # Step 6: Score and batch-insert into buffer
        # Seeds: max priority (or actual SFL for competitive mode)
        # Mutations: actual SFL score via 10-rollout eval (standard buffer competition)
        # ---------------------------------------------------------------
        retained_seeds = 0
        retained_mutations = 0

        # --- Insert seeds (ancestor IDs assigned before step 5) ---
        if valid_levels:
            if mode == "competitive":
                # Competitive: use actual SFL scores from gate evaluation
                seed_scores_arr = jnp.array(seed_sfl_scores, dtype=jnp.float32)
            else:
                # Non-competitive: max priority to force replay
                buf_size = int(np.asarray(sampler["size"]))
                if buf_size > 0:
                    max_score = float(np.asarray(sampler["scores"][:buf_size]).max())
                else:
                    max_score = 1.0
                inject_score = max_score + 1e-4
                seed_scores_arr = jnp.full(len(valid_levels), inject_score, dtype=jnp.float32)

            seed_batch = jax.tree_util.tree_map(
                lambda *xs: jnp.stack(xs), *valid_levels
            )
            seed_extras = {
                "ancestor_id": jnp.array(seed_ancestor_ids, dtype=jnp.int32),
                "max_return": jnp.full(len(valid_levels), -jnp.inf),
            }
            new_sampler, seed_indices = self.level_sampler.insert_batch(
                sampler, seed_batch, seed_scores_arr, level_extras=seed_extras
            )
            retained_seeds = int(jnp.sum(seed_indices >= 0))
            train_state = train_state.replace(sampler=new_sampler)
            sampler = new_sampler

            # Update numpy provenance arrays for seeds (origin=1)
            if hasattr(self, '_buffer_origins') and self._buffer_origins is not None:
                for i, slot in enumerate(np.asarray(seed_indices)):
                    if slot >= 0:
                        self._buffer_origins[slot] = 1  # LLM original
                        self._buffer_ancestor_ids[slot] = seed_ancestor_ids[i]

        # --- Filter mutations by buffer_min SFL, then force-insert passing ones ---
        if mutation_levels and self.agent_evaluator is not None:
            logger.info(f"[LLM] Scoring {len(mutation_levels)} mutations via 10-rollout SFL eval...")
            buf_size = int(np.asarray(sampler["size"]))
            buf_min_score = float(np.asarray(sampler["scores"][:buf_size]).min()) if buf_size > 0 else 0.0
            buf_max_score = float(np.asarray(sampler["scores"][:buf_size]).max()) if buf_size > 0 else 1.0
            inject_score = buf_max_score + 1e-4  # max-priority to guarantee insertion

            passing_levels = []
            passing_ancestor_ids = []
            mut_sfl_scores = []
            mut_rejected_sfl = 0
            for idx_m, mut_level in enumerate(mutation_levels):
                traj = self.agent_evaluator.evaluate_level_multi_rollout(mut_level, n_rollouts=10)
                p = traj.get("solve_rate", 0.0)
                sfl = p * (1.0 - p)
                mut_sfl_scores.append(sfl)
                if sfl >= buf_min_score:
                    passing_levels.append(mut_level)
                    passing_ancestor_ids.append(mutation_ancestor_ids[idx_m])
                else:
                    mut_rejected_sfl += 1

            logger.info(f"[LLM] Mutation SFL filter: {len(passing_levels)}/{len(mutation_levels)} passed "
                        f"(>= buffer_min {buf_min_score:.4f}), "
                        f"{mut_rejected_sfl} rejected, mean SFL={np.mean(mut_sfl_scores):.4f}")

            if passing_levels:
                # Direct buffer write: find slots with lowest raw scores and overwrite them.
                # Bypasses PLR weight-based insertion which fights freshness/staleness.
                buf_size = int(np.asarray(sampler["size"]))
                raw_scores = np.asarray(sampler["scores"][:buf_size])
                # Sort by score ascending — weakest first
                weakest_slots = np.argsort(raw_scores)
                n_to_insert = min(len(passing_levels), len(weakest_slots))

                mut_batch = jax.tree_util.tree_map(
                    lambda *xs: jnp.stack(xs), *passing_levels[:n_to_insert]
                )
                target_slots = jnp.array(weakest_slots[:n_to_insert], dtype=jnp.int32)

                # Write levels, scores, extras directly into target slots
                new_levels = sampler["levels"]
                for i in range(n_to_insert):
                    slot = int(target_slots[i])
                    level_i = jax.tree_util.tree_map(lambda x: x[i], mut_batch)
                    new_levels = jax.tree_util.tree_map(
                        lambda buf, val: buf.at[slot].set(val), new_levels, level_i)

                new_scores = sampler["scores"].at[target_slots].set(
                    jnp.full(n_to_insert, inject_score, dtype=jnp.float32))
                new_timestamps = sampler["timestamps"].at[target_slots].set(
                    jnp.full(n_to_insert, sampler["episode_count"] + 1, dtype=jnp.int32))

                new_extras = sampler["levels_extra"]
                new_anc = new_extras["ancestor_id"].at[target_slots].set(
                    jnp.array(passing_ancestor_ids[:n_to_insert], dtype=jnp.int32))
                new_maxret = new_extras["max_return"].at[target_slots].set(
                    jnp.full(n_to_insert, -jnp.inf))
                new_extras = {**new_extras, "ancestor_id": new_anc, "max_return": new_maxret}

                new_sampler = {**sampler,
                               "levels": new_levels,
                               "scores": new_scores,
                               "timestamps": new_timestamps,
                               "levels_extra": new_extras,
                               "episode_count": sampler["episode_count"] + n_to_insert}
                retained_mutations = n_to_insert
                train_state = train_state.replace(sampler=new_sampler)
                sampler = new_sampler
                logger.info(f"[LLM] Mutations: {retained_mutations}/{len(passing_levels)} inserted "
                            f"(direct write to {n_to_insert} weakest slots, "
                            f"mean SFL={np.mean(mut_sfl_scores):.4f})")

                # Update numpy provenance arrays
                if hasattr(self, '_buffer_origins') and self._buffer_origins is not None:
                    for i in range(n_to_insert):
                        slot = int(target_slots[i])
                        self._buffer_origins[slot] = 2  # LLM mutation descendant
                        self._buffer_ancestor_ids[slot] = passing_ancestor_ids[i]
        elif mutation_levels:
            # No agent evaluator (gate disabled) — insert with max priority (legacy fallback)
            buf_size = int(np.asarray(sampler["size"]))
            max_score = float(np.asarray(sampler["scores"][:buf_size]).max()) if buf_size > 0 else 1.0
            inject_score = max_score + 1e-4
            mut_batch = jax.tree_util.tree_map(
                lambda *xs: jnp.stack(xs), *mutation_levels
            )
            mut_scores_arr = jnp.full(len(mutation_levels), inject_score, dtype=jnp.float32)
            mut_extras = {
                "ancestor_id": jnp.array(mutation_ancestor_ids[:len(mutation_levels)], dtype=jnp.int32),
                "max_return": jnp.full(len(mutation_levels), -jnp.inf),
            }
            new_sampler, mut_indices = self.level_sampler.insert_batch(
                sampler, mut_batch, mut_scores_arr, level_extras=mut_extras
            )
            retained_mutations = int(jnp.sum(mut_indices >= 0))
            train_state = train_state.replace(sampler=new_sampler)
            sampler = new_sampler

            # Update numpy provenance arrays for mutations (origin=2)
            if hasattr(self, '_buffer_origins') and self._buffer_origins is not None:
                for i, slot in enumerate(np.asarray(mut_indices)):
                    if slot >= 0:
                        self._buffer_origins[slot] = 2
                        self._buffer_ancestor_ids[slot] = mutation_ancestor_ids[i]

        retained_count = retained_seeds + retained_mutations
        retained_rate = retained_count / total_levels_to_inject if total_levels_to_inject > 0 else 0.0

        if total_levels_to_inject == 0:
            logger.warning("[LLM] No levels accepted for injection this event")

        # ---------------------------------------------------------------
        # Step 5b: Update fixed_distribution and proximity gate for online injection
        # ---------------------------------------------------------------
        if retained_count > 0 and self.training_config is not None:
            # Update fixed distribution slot count on train_state (JIT-visible)
            if self.training_config.get("fixed_distribution"):
                buf_size = int(np.asarray(sampler["size"]))
                ancestor_ids = np.asarray(sampler["levels_extra"]["ancestor_id"][:buf_size])
                n_llm_in_buffer = int((ancestor_ids >= 0).sum())
                if n_llm_in_buffer > 0 and buf_size > 0:
                    injection_pct = n_llm_in_buffer / buf_size
                    n_train_envs = self.training_config.get("num_train_envs", 32)
                    n_llm_slots = max(1, round(injection_pct * n_train_envs))
                    train_state = train_state.replace(
                        fixed_dist_n_llm=jnp.int32(n_llm_slots))
                    print(f"[LLM] Fixed distribution updated: {injection_pct:.1%} LLM in buffer -> "
                          f"{n_llm_slots}/{n_train_envs} replay slots",
                          flush=True)

            # Register seed embeddings for proximity gate (reuse cache from step 5)
            if prox_ratio > 0 and valid_levels and seed_emb_cache:
                max_anc = self.training_config.get("max_llm_ancestors", 256)
                seed_embs = np.array(train_state.seed_embeddings, copy=True)
                prox_thresholds = np.array(train_state.proximity_thresholds, copy=True)

                for i in range(len(valid_levels)):
                    anc_id = seed_ancestor_ids[i]
                    if anc_id >= max_anc or i not in seed_emb_cache:
                        continue
                    emb, threshold = seed_emb_cache[i]
                    seed_embs[anc_id] = emb
                    prox_thresholds[anc_id] = threshold
                    print(f"[LLM] Seed ancestor {anc_id}: threshold={threshold:.4f}", flush=True)

                n_seeds = int((prox_thresholds < np.inf).sum())
                train_state = train_state.replace(
                    seed_embeddings=jnp.array(seed_embs),
                    proximity_thresholds=jnp.array(prox_thresholds),
                    n_seeds=jnp.int32(n_seeds),
                )
                print(f"[LLM] Registered {len(valid_levels)} new seed embeddings "
                      f"({n_seeds} total ancestors)", flush=True)

        # ---------------------------------------------------------------
        # Step 6: Update counters and WandB logging
        # ---------------------------------------------------------------
        self.total_injected += retained_count
        self.total_attempted += total_levels_to_inject
        injection_time = time.time() - injection_start

        acceptance_rate = seeds_valid / seeds_generated if seeds_generated > 0 else 0.0
        mutation_survival_rate = (
            mutations_solvable / mutations_generated
            if mutations_generated > 0 else 0.0
        )

        log_payload = {
            "llm/injected_count": retained_count,
            "llm/retained_seeds": retained_seeds,
            "llm/retained_mutations": retained_mutations,
            "llm/seeds_generated": seeds_generated,
            "llm/seeds_valid": seeds_valid,
            "llm/mutations_generated": mutations_generated,
            "llm/mutations_solvable": mutations_solvable,
            "llm/acceptance_rate": acceptance_rate,
            "llm/retained_rate": retained_rate,
            "llm/injection_time_seconds": injection_time,
            "llm/total_injected": self.total_injected,
            "llm/mutation_survival_rate": mutation_survival_rate,
            "llm/mutations_prox_rejected": mutations_prox_rejected,
            # Gate-specific metrics (GATE-03)
            "llm/diversity_score_mean": float(np.mean(diversity_scores)) if diversity_scores else 0.0,
            "llm/difficulty_score_mean": float(np.mean(difficulty_scores)) if difficulty_scores else 0.0,
            "llm/gate_rejection_rate": gate_rejected / seeds_generated if seeds_generated > 0 else 0.0,
            "llm/batch_all_rejected_count": self.batch_all_rejected_count,
            "llm/effective_difficulty_threshold": effective_threshold if effective_threshold is not None else 0.0,
            "llm/effective_diversity_threshold": effective_diversity if effective_diversity is not None else 0.0,
            "llm/difficulty_gate_mode": mode,
            "llm/diversity_gate_mode": div_mode,
        }

        # Embedding L2 distance stats across accepted seeds
        if emb_min_dists:
            log_payload["llm/emb_l2_min_of_mins"] = float(np.min(emb_min_dists))
            log_payload["llm/emb_l2_mean_of_mins"] = float(np.mean(emb_min_dists))
            log_payload["llm/emb_l2_max_of_mins"] = float(np.max(emb_min_dists))
            log_payload["llm/emb_l2_mean_of_means"] = float(np.mean(emb_mean_dists))
            log_payload["llm/emb_l2_mean_of_medians"] = float(np.mean(emb_median_dists))
            log_payload["llm/emb_l2_mean_of_maxs"] = float(np.mean(emb_max_dists))

        # Add wall_map hash table to log_payload for audit trail (EXPT-02)
        # Guard against empty list to avoid logging empty WandB tables.
        if accepted_hashes:
            hash_table = wandb.Table(
                columns=["step", "batch_index", "wall_map_hash"],
                data=[[current_step, i, h] for i, h in enumerate(accepted_hashes)]
            )
            log_payload["llm/accepted_level_hashes"] = hash_table

        try:
            log_payload["num_updates"] = current_step
            wandb.log(log_payload)
        except Exception:
            # wandb not yet initialized (e.g., dry-run tests) — log locally
            logger.info(f"[LLM] WandB unavailable, metrics: {log_payload}")

        print(
            f"[LLM] Injection complete in {injection_time:.1f}s: "
            f"injected={retained_count}, acceptance={acceptance_rate:.0%}, "
            f"retained={retained_rate:.0%}, total={self.total_injected}",
            flush=True
        )

        return (rng, train_state)
